on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DD_ACCOUNT_ID=${{ secrets.PROD_DD_ACCOUNT_ID }} \
            --build-arg DD_CLIENT_TOKEN=${{ secrets.PROD_DD_CLIENT_TOKEN }} \
            -t your-image-name .
